const router = require("express").Router();
const { CategoryController } = require("../../http/controller/admin/category.controller");
router.post("/create", CategoryController.createCategory);
router.get("/getParent", CategoryController.getParent);
router.get("/getByID/:id", CategoryController.getCategoryByID);
router.get("/getAllCategoryV1", CategoryController.getAllCategoryV1);
router.get("/getAllCategoryV2", CategoryController.getAllCategoryV2);
router.get("/getAllCategoryV3", CategoryController.getAllCategoryV3);
router.patch("/update/:id", CategoryController.updateCategory);
router.delete("/deleteByID/:id", CategoryController.deleteByID);
module.exports = { CategoryRoutes: router };
